os:
  - linux

language: node_js

node_js:
  - 10

cache: npm

script:
  - npm run lint
  - npm run build
  - npm run test
  - npm run semantic-release

# jobs:
#   include:
#     - stage: build
#       script:
#         - npm run lint
#         - npm run build
#         - npm run test

#     - stage: release
#       # node_js: lts/*
#       script:
#         - npm run semantic-release
