name: Continuous

on: [push]

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Clean install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Bootstrap
        run: npm run bootsrap

      - name: Test
        run: npm run test

      - name: Start server in the background
        run: npm run testing:server &

      - uses: cypress-io/github-action@v2
        with:
          working-directory: packages/testing
