name: Documentation

# on:
#   push:
#     branches:
#       - master

on: [push]

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: baloise/design-system-docs:${{ GITHUB_SHA }}

      - name: Publish
        uses: mosteo-actions/docker-run@v1
        with:
          image: baloise/gitopscli:latest
          command: |
            gitopscli deploy
            --git-provider-url https://github.com/baloise-incubator \
            --username ${{ secrets.GITOPSCLI_USERNAME }} \
            --password ${{ secrets.GITOPSCLI_PASSWORD }} \
            --git-user "GitOps CLI" \
            --git-email "gitopscli@baloise.dev" \
            --organisation "baloise-incubator" \
            --repository-name "okd4-example-apps" \
            --file "baloise-design-system-docs-test/values.yaml" \
            --values "{baloise-design-system-docs.tag: ${{ GITHUB_SHA }}}"
